### ISSUE TITLE
Sort team members according to the contributions

### ISSUE THREAD

**Issue by ashwini0529** [rahulakrishna/gdginfo#5]
Maybe commits, reviews, PRs, anything would work. Arranging alphabetically is not cool.

**Comment by rahulakrishna** [comment]
That's a very good idea. @apuayush  already has implemented a mechanism to calculate a score for every member. We can use that. Need the backend hosted though.

**Comment by ashwini0529** [comment]
@shubham0704 @apuayush What's the status with backend? I guess you should host it on heroku and see if it works.

**Comment by shubham0704** [comment]
Api hosted sharing link on slack .Fixed. Close when you feel like. :+1:

**Comment by apuayush** [comment]
https://radiant-harbor-42641.herokuapp.com/leaderboard - for leaderboard
https://radiant-harbor-42641.herokuapp.com/topcontributors - for topcontributors
api is showing 23 members ryt now because there are 36 non-private members out of which 23 are contributing on some project at the time we launched the server . And some repositories like way2sms_API are not displayed because they have zero contributors...

**Comment by shubham0704** [comment]
@apuayush ping me for changes if any.

**Comment by apuayush** [comment]
okay.. did u clear the database before launching . if not still no problem . just i want to know .

**Comment by shubham0704** [comment]
No

**Comment by apuayush** [comment]
okay ... its working fine then
